name: Deploy contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network"
        required: true
        type: choice
        options:
          - hardhat
          - arbitrumSepolia
          - tenderlyVirtualArbitrumSepolia
        default: "hardhat"

jobs:
  build-and-test:
    uses: ./.github/workflows/main.yml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ${{ inputs.network }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - name: Build contracts
        run: pnpm run build

      - name: Deploy contracts on Hardhat (dry-run)
        if: inputs.network == 'hardhat'
        run: pnpm run deploy

      - name: Deploy contracts
        if: inputs.network != 'hardhat'
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
        run: pnpm hardhat run scripts/deploy.ts --network ${{ inputs.network }}

      - name: Save deployment artifacts
        if: inputs.network != 'hardhat' && inputs.network != 'tenderlyVirtualArbitrumSepolia'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: save deployment artifacts for ${{ inputs.network }} (Github run_id: ${{ github.run_id }})"
          file_pattern: "ignition/deployments/"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"

      # TODO enable verification when scripts supports it
      # - name: Verify contracts
      #   if: inputs.network != 'hardhat' && inputs.network != 'tenderlyVirtualArbitrumSepolia'
      #   continue-on-error: true
      #   env:
      #     ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      #     RPC_URL: ${{ secrets.RPC_URL }}
      #   run: |
      #     make verify-all-${{ inputs.network }}
