name: License check

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-license-check
  cancel-in-progress: true

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - run: corepack enable # Use package manager defined in package.json
      - run: pnpm install --frozen-lockfile

      - name: Check licenses
        run: npx license-checker@25.0.1 --onlyAllow 'MIT;Apache-2.0;'
