# ⚠️ THIS WORKFLOW IS THE TRUSTED PUBLISHER CONFIGURED ON NPMJS.COM, DO NOT RENAME OR DELETE THIS FILE ⚠️

name: Publish NPM Package

on:
  push:
    tags:
      - "v*"

jobs:
  pre-publish:
    uses: ./.github/workflows/main.yml

  publish-setup:
    needs: pre-publish
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.get-node-version.outputs.NODE_VERSION }}
      TAG: ${{ steps.get-dist-tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v5
      - name: Determine Node.js version
        id: get-node-version
        run: echo "NODE_VERSION=`cat .nvmrc`" >> $GITHUB_OUTPUT
      - name: Determine package dist tag
        id: get-dist-tag
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" == *"-rc"* ]]; then
            echo "TAG=rc" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: publish-setup
    permissions:
      id-token: write # Required for OIDC
      packages: write
      contents: read
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/publish-npm.yml@publish-npm-v1.6.0
    with:
      node-version: ${{ needs.publish-setup.outputs.NODE_VERSION }}
      scope: "@iexec-nox"
      tag: ${{ needs.publish-setup.outputs.TAG }}
      install-command: corepack enable && pnpm install --frozen-lockfile
      build-command: pnpm run build
      run-tests: false # Tests already run in the pre-publish job
      test-command: "pnpm run test"
      lint-command: "pnpm run --if-present lint"
      type-check-command: "pnpm run --if-present check-types"
      format-check-command: pnpm run format:check
