name: Set KMS Public Key

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network where contracts are deployed"
        required: true
        type: choice
        options:
          - tenderlyArbitrumSepolia
          - arbitrumSepolia
          - sepolia
        default: "tenderlyArbitrumSepolia"

jobs:
  set-kms-public-key:
    runs-on: ubuntu-latest
    environment: ${{ inputs.network }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - name: Build contracts
        run: pnpm run build

      - name: Set KMS public key
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.UPGRADER_PRIVATE_KEY }}
        run: pnpm run set-kms-public-key --network ${{ inputs.network }}
